# Generated by Django 5.1.7 on 2025-04-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_is_closed_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_closed',
        ),
    ]
